# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 403031211514c01490d9d1bdca2a4ce3d6db187ac7e3109329db7e938498688d28c4e7ed08a25e8575b85ac741dfc38204ee5cb025aafea58db90b27e775a50d

test:
  secret_key_base: fb6da6f240ec71e15697f351c7f409f2e440cf46a89bd7e14e5201b0b3cecf08d86247c6efe40c9eab99ba55e7fa9968498eb5f292408ce4847f4f0696372d39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
